version: "3.5"

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - default

  web:
    container_name: dockerdev
    build: ./
    ports:
      - "8080:8080"
    environment:
      DD_DB_HOST: db
    command: /server
    restart: on-failure
    depends_on:
      - database

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "5050:80"

volumes:
  database_postgres: